import { randomInt } from 'es-toolkit';
import { AnimatePresence, motion } from 'motion/react';
import Image from 'next/image';
import { useEffect, useMemo, useState } from 'react';

const previews = [
  {
    src: '/developer_feedback/developer_feedback_preview.jpg',
    id: 'developer feedback preview',
  },
  {
    src: '/developer_feedback/grid_preview.jpg',
    id: 'grid preview',
  },
  {
    src: '/examples/cyberpunkctf_preview.jpg',
    id: 'cyberpunkctf preview',
  },
  {
    src: '/examples/daisukicms1.jpg',
    id: 'daisuki cms',
  },
  {
    src: '/examples/fareastctf1.jpg',
    id: 'fareastctf',
  },
  {
    src: '/fareastctf/fareastctf_registration.png',
    id: 'fareastctf registration',
  },
  {
    src: '/fareastctf/hacker.png',
    id: 'fareastctf hacker',
  },
  {
    src: '/fareastctf/lms_preview.png',
    id: 'lms preview',
  },
  {
    src: '/no-signal.jpg',
    id: 'no signal',
  },
];

export type Props = {
  staggerDelay?: number;
  updateDelay?: number;

  screenCount?: number;
};

export type TVScreenProps = {
  index: number;
  screenCount: number;
  previewIndex: number;

  staggerDelay: number;
  updateDelay: number;
};

const staggerDelay = 50;
const updateDelay = 1000;

export function TVScreen(p: TVScreenProps) {
  const [previewIndex, setPreviewIndex] = useState(p.previewIndex);
  const preview = previews[previewIndex];

  useEffect(() => {
    setTimeout(
      () => {
        const newPreviewIndex = randomInt(previews.length);

        if (newPreviewIndex == previewIndex) {
          setPreviewIndex((previewIndex + 1) % previews.length);
          return;
        }

        setPreviewIndex(newPreviewIndex);
      },
      updateDelay + p.screenCount * staggerDelay,
    );
  }, [p.screenCount, previewIndex]);

  return (
    <motion.div
      className="relative aspect-video w-full bg-neutral-800 overflow-hidden rounded-lg
        p-1"
    >
      <div className="relative w-full h-full overflow-hidden rounded-lg">
        <div
          className="absolute top-0 left-0 w-full h-full z-10"
          style={{
            background: 'radial-gradient(transparent, rgba(0,0,0,0.2))',
          }}
        />
        <AnimatePresence>
          <motion.div
            key={preview.id}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{
              delay: p.index * (staggerDelay / 1000),
            }}
          >
            <Image src={preview.src} alt={preview.id} style={{ objectFit: 'cover' }} fill />
          </motion.div>
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

export default function TVs(p: Props) {
  const { staggerDelay = 50, updateDelay = 1000, screenCount = 48 } = p;

  const screens = useMemo(() => {
    return new Array(screenCount).fill(0).map((_, index) => {
      return (
        <TVScreen
          // biome-ignore lint/suspicious/noArrayIndexKey: generated by fill.map
          key={index}
          screenCount={screenCount}
          index={index}
          previewIndex={index % previews.length}
          staggerDelay={staggerDelay}
          updateDelay={updateDelay}
        />
      );
    });
  }, [staggerDelay, updateDelay, screenCount]);

  return (
    <div className="absolute top-0 left-0 w-full h-full grid grid-cols-4 auto-rows-max gap-2 blur-[2px]">
      {screens}
    </div>
  );
}
